### ISSUE TITLE
What to do about pull requests on Eric's KineticJS

### ISSUE THREAD

**Issue by leohenning** [lavrton/KineticJS#5]
I had a pull request on Eric's Kinetic GIT page. What should I do? Is there an easy way to move it over?

**Comment by jovination** [comment]
I am far from an expert on git, but here is a thought on what I might do (or at least try).

fork this repository and change the remote in you local to point to that repository, then merge. This should allow you to make the same pull request to this repo.

There are commands to do this, but typically I just edit `.git/CONFIG` easier and less room for error, since this repository is just another fork, most of the commits will sync over.

**Comment by lavrton** [comment]
@leohenning are you talking about this request: https://github.com/ericdrowell/KineticJS/pull/1043?

I will merge soon.

**Comment by lavrton** [comment]
Merged. I change api from `offsets` to `frameOffsets`.
